# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\"\n\x14Recommendations_list\x12\n\n\x02id\x18\x01 \x03(\x03\"\x19\n\x07rec4msg\x12\x0e\n\x06\x61\x64v_id\x18\x01 \x03(\x03\"4\n\x10rec4msg_category\x12\x0e\n\x06\x61\x64v_id\x18\x01 \x03(\x03\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"\x06\n\x04void2\x9c\x01\n\x0fRecommendations\x12:\n\x15UpdateRecommendations\x12\x08.rec4msg\x1a\x15.Recommendations_list\"\x00\x12M\n\x1fUpdateRecommendationsByCategory\x12\x11.rec4msg_category\x1a\x15.Recommendations_list\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECOMMENDATIONS_LIST']._serialized_start=17
  _globals['_RECOMMENDATIONS_LIST']._serialized_end=51
  _globals['_REC4MSG']._serialized_start=53
  _globals['_REC4MSG']._serialized_end=78
  _globals['_REC4MSG_CATEGORY']._serialized_start=80
  _globals['_REC4MSG_CATEGORY']._serialized_end=132
  _globals['_VOID']._serialized_start=134
  _globals['_VOID']._serialized_end=140
  _globals['_RECOMMENDATIONS']._serialized_start=143
  _globals['_RECOMMENDATIONS']._serialized_end=299
# @@protoc_insertion_point(module_scope)
