# Generated by Django 5.0.4 on 2024-05-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPUvito', '0002_initial'),
        ('users', '0002_alter_adverstiment_order_image_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='adv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.adverstiment'),
            preserve_default=False,
        ),
    ]
